# Generated by Django 4.2.6 on 2024-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_name', models.IntegerField()),
                ('client', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sity', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('home', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('flat', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'В обработке'), (1, 'Принят'), (2, 'Готовится'), (3, 'Передан курьеру'), (4, 'Ждет курьера'), (5, 'Доставлен'), (6, 'Отказан'), (7, 'Отменен')])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Менеджер'), (1, 'Заказчик'), (2, 'Доставщик'), (3, 'Кухня')])),
            ],
        ),
    ]
