# Generated by Django 4.2.6 on 2024-04-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
