# Generated by Django 4.2.6 on 2024-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Принят'), (1, 'Готовится'), (2, 'Передан курьеру'), (3, 'Доставлен')]),
        ),
    ]
