# Generated by Django 4.2.6 on 2024-04-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0003_alter_orderinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='megapizza.orderstatus'),
        ),
    ]
