# Generated by Django 4.2.6 on 2024-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0004_orderstatus_alter_orderinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
