# Generated by Django 4.2.6 on 2024-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0006_alter_orderinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='client',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='deliver_name',
            field=models.TextField(),
        ),
    ]
