# Generated by Django 4.2.6 on 2024-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0007_alter_orderinfo_client_alter_orderinfo_deliver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
