# Generated by Django 4.2.6 on 2024-04-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('megapizza', '0008_alter_orderstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='comment',
            field=models.TextField(),
        ),
    ]
