# Generated by Django 4.2.6 on 2024-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0011_corf_alter_orderinfo_status_delete_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(choices=[('0', 'Принят'), ('1', 'На кухне'), ('2', 'У курьера'), ('3', 'Доставлен'), ('4', 'Отменён'), ('5', 'Не обработан')], max_length=3),
        ),
    ]
