# Generated by Django 4.2.6 on 2024-04-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0012_alter_orderinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
