# Generated by Django 4.2.6 on 2024-04-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megapizza', '0013_alter_orderinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(upload_to='megapizzaproject\\megapizza\\static\\images'),
        ),
    ]
